# This question is asked by Google. You are given two strings, s and t which only consist of lowercase letters. 
# t is generated by shuffling the letters in s as well as potentially adding an additional random character. 
# Return the letter that was randomly added to t if it exists, otherwise, return ’ ‘.
# Note: You may assume that at most one additional character can be added to t.

# s = "foobar", t = "barfoot", return 't'
# s = "ide", t = "idea", return 'a'
# s = "coding", t "ingcod", return '
from collections import Counter
def spot_the_difference(s,t):
    d = {}
    if len(s) == len(t):
        return " "
    s_ = Counter(s)
    t_ = Counter(t)
    val = Counter(t) - Counter(s)
    for i in val.keys():
        return i

 
    



print(spot_the_difference("foobar","barfoot"))
print(spot_the_difference("ide","idea"))
print(spot_the_difference("coding","ingcod"))
